name: Feature Ask Simple
description: Quick feature ask with a single description field.
title: "[Feature Ask]: "
labels:
  - triage
body:
  - type: textarea
    id: issue_description
    attributes:
      label: Issue Description
      description: Describe the issue or feature ask in a few lines.
      placeholder: |
        Please add version number in the navbar as well.
        It would help when sharing screenshots with the team.
    validations:
      required: true
